## Data Merge

In [5]:
import pandas as pd
data1 = {
    'id': [1,2,3],
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35]
}
df1 = pd.DataFrame(data1)
df1.head()

   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35

In [6]:
data2 = {
    'id':[1,2,3],
    'salary': [50000, 60000, 70000],
    'department': ['HR', 'Engineering', 'Marketing']
}
df2 = pd.DataFrame(data2)
df2.head()

   id  salary   department
0   1   50000           HR
1   2   60000  Engineering
2   3   70000    Marketing

In [7]:
# merging dataframes on 'id'
merged_df = pd.merge(df1, df2, on='id', how='inner')
merged_df.head()

   id     name  age  salary   department
0   1    Alice   25   50000           HR
1   2      Bob   30   60000  Engineering
2   3  Charlie   35   70000    Marketing

## Concatenation

In [9]:
import pandas as pd

# Example datasets for Pakistani context
# Dataset 1 - Pakistani Names and Ages
data1 = {'Name': ['Ahmed', 'Fatima', 'Ali'], 'Age': [28, 32, 24]}
# Dataset 2 - More Pakistani Names and Ages
data2 = {'Name': ['Sara', 'Usman', 'Aisha'], 'Age': [29, 35, 27]}
# Dataset 3 - Cities and Provinces in Pakistan
data3 = {'City': ['Karachi', 'Lahore', 'Islamabad'], 'Province': ['Sindh', 'Punjab', 'Islamabad']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

# Concatenating Rows
concatenated_rows = pd.concat([df1, df2])

# Concatenating Columns
# Note: For a meaningful column-wise concatenation, dataframes should have the same number of rows.
concatenated_columns = pd.concat([df1, df3], axis=1)
print(concatenated_rows)
print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
concatenated_columns

     Name  Age
0   Ahmed   28
1  Fatima   32
2     Ali   24
0    Sara   29
1   Usman   35
2   Aisha   27
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

     Name  Age       City   Province
0   Ahmed   28    Karachi      Sindh
1  Fatima   32     Lahore     Punjab
2     Ali   24  Islamabad  Islamabad

## Data Joining

In [3]:
# data joining
import pandas as pd
data1 = {
    'id': [1,2,3],
    'name': ['Ahmed', 'Fatima', 'Ali'],
    'age': [28, 32, 24]
}
df1 = pd.DataFrame(data1)
df1.head()

data2 = {
    'id':[1,2,3],
    'salary': [50000, 60000, 70000],
    'department': ['HR', 'Engineering', 'Marketing']
}
df2 = pd.DataFrame(data2)
df2.head()

   id  salary   department
0   1   50000           HR
1   2   60000  Engineering
2   3   70000    Marketing

In [5]:
# joining df1 and df2  using join function
joined_df = df1.set_index('id').join(df2.set_index('id'), how='inner')
joined_df.reset_index(inplace=True)
joined_df.head()

   id    name  age  salary   department
0   1   Ahmed   28   50000           HR
1   2  Fatima   32   60000  Engineering
2   3     Ali   24   70000    Marketing